import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { forkJoin, finalize } from 'rxjs';
import { ButtonModule } from 'primeng/button';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import { TextareaModule } from 'primeng/textarea';
import { BkpPageHeaderComponent } from '../../components/bkp-ui.component';
import { BkpRepository } from '../../data-access/bkp.repository';
import { BkpConfirmService } from '../../services/bkp-confirm.service';
import { PendingChangesAware } from '../../guards/pending-changes.guard';
import { jsonPretty, parseJsonObject } from '../../data-access/bkp.shared';
import { NotifyService } from 'src/app/core/services/notify.service';
@Component({selector:'app-bkp-notifications',standalone:true,imports:[CommonModule,FormsModule,ButtonModule,ConfirmDialogModule,TextareaModule,BkpPageHeaderComponent],templateUrl:'./notifications.component.html',styleUrl:'./notifications.component.scss'})
export class BkpNotificationsComponent implements OnInit,PendingChangesAware{private repo=inject(BkpRepository);private confirm=inject(BkpConfirmService);private notify=inject(NotifyService);tab=signal<'contacts'|'rules'|'integrations'>('contacts');loading=signal(false);saving=signal(false);dirty=signal(false);contacts=signal<any[]>([]);rules=signal<any[]>([]);integrations=signal<any[]>([]);selected=signal<any|null>(null);jsonText=signal('{}');initial='{}';ngOnInit(){this.cargar();}canDeactivate(){return !this.dirty()||this.confirm.confirmDiscard();}cargar(){this.loading.set(true);forkJoin({contacts:this.repo.listarContacts('',0,100,null),rules:this.repo.listarRules('',0,100,null),integrations:this.repo.listarIntegrations('',0,100,null)}).pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>{this.contacts.set(r.contacts.items??[]);this.rules.set(r.rules.items??[]);this.integrations.set(r.integrations.items??[]);}});}items(){return this.tab()==='contacts'?this.contacts():this.tab()==='rules'?this.rules():this.integrations();}idField(){return this.tab()==='contacts'?'idBkpNotificationContact':this.tab()==='rules'?'idBkpNotificationRule':'idBkpIntegrationProvider';}nuevo(){this.selected.set(null);this.jsonText.set(jsonPretty(this.tab()==='contacts'?{nombre:'Soporte',canal:'EMAIL',destinatario:'soporte@empresa.com',activo:true}:this.tab()==='rules'?{nombre:'Avisar fallos',eventType:'BACKUP_FAILED',idBkpNotificationContactFk:null,idBkpIntegrationProviderFk:null,onlyForPlanId:null,activo:true}:{nombre:'SMTP principal',providerType:'SMTP',baseUrl:'',sessionName:'',idBkpSecretAuthFk:null,configJson:{},activo:true}));this.refresh();}seleccionar(i:any){this.selected.set(i);this.jsonText.set(jsonPretty(i));this.refresh();}guardar(){const p=parseJsonObject(this.jsonText());const id=Number(this.selected()?.[this.idField()]??0);delete (p as any)[this.idField()];const req=this.tab()==='contacts'?(id?this.repo.editarContact(id,p):this.repo.crearContact(p)):this.tab()==='rules'?(id?this.repo.editarRule(id,p):this.repo.crearRule(p)):(id?this.repo.editarIntegration(id,p):this.repo.crearIntegration(p));this.saving.set(true);req.pipe(finalize(()=>this.saving.set(false))).subscribe({next:r=>{this.notify.success('Guardado',r.mensaje);this.dirty.set(false);this.cargar();},error:e=>this.notify.error('No se pudo guardar',e?.message)});}onChange(v:string){this.jsonText.set(v);this.dirty.set(v!==this.initial);}refresh(){this.initial=this.jsonText();this.dirty.set(false);}}
