import { Injectable, inject } from '@angular/core';
import { map } from 'rxjs';
import { BkpApi } from './bkp.api';
import { BkpAgentNode, BkpEngineTool, BkpGeneralConfig, BkpIntegrationProvider, BkpNotificationContact, BkpNotificationRule, BkpPlanGuardarRequest, BkpRestoreRequest, BkpSchedule, BkpSecretEditarRequest, BkpSecretGuardarRequest, BkpSourceDatabase, BkpStorageDestination } from './bkp.models';
import { unwrapOrThrow, unwrapWithMsg } from './bkp.shared';

@Injectable({ providedIn:'root' })
export class BkpRepository{
  private api=inject(BkpApi);
  catalogos(){return this.api.catalogos().pipe(map(unwrapOrThrow));}
  listarSecrets(q='',page=0,size=100,activo:boolean|null=null){return this.api.listarSecrets({q,page,size,activo}).pipe(map(unwrapOrThrow));} crearSecret(p:BkpSecretGuardarRequest){return this.api.crearSecret(p).pipe(map(unwrapWithMsg));} editarSecret(p:BkpSecretEditarRequest){return this.api.editarSecret(p).pipe(map(unwrapWithMsg));} eliminarSecret(id:number){return this.api.eliminarSecret(id).pipe(map(unwrapWithMsg));}
  listarAgents(q='',page=0,size=100,activo:boolean|null=null){return this.api.listarAgents({q,page,size,activo}).pipe(map(unwrapOrThrow));} crearAgent(p:Partial<BkpAgentNode>){return this.api.crearAgent(p).pipe(map(unwrapWithMsg));} editarAgent(id:number,c:Record<string,unknown>){return this.api.editarAgent(id,c).pipe(map(unwrapWithMsg));} eliminarAgent(id:number){return this.api.eliminarAgent(id).pipe(map(unwrapWithMsg));} probarConexionAgent(id:number){return this.api.probarConexionAgent(id).pipe(map(unwrapWithMsg));}
  listarTools(q='',page=0,size=100,activo:boolean|null=null){return this.api.listarTools({q,page,size,activo}).pipe(map(unwrapOrThrow));} crearTool(p:Partial<BkpEngineTool>){return this.api.crearTool(p).pipe(map(unwrapWithMsg));} editarTool(id:number,c:Record<string,unknown>){return this.api.editarTool(id,c).pipe(map(unwrapWithMsg));} eliminarTool(id:number){return this.api.eliminarTool(id).pipe(map(unwrapWithMsg));}
  listarSources(q='',page=0,size=100,activo:boolean|null=null){return this.api.listarSources({q,page,size,activo}).pipe(map(unwrapOrThrow));} crearSource(p:Partial<BkpSourceDatabase>){return this.api.crearSource(p).pipe(map(unwrapWithMsg));} editarSource(id:number,c:Record<string,unknown>){return this.api.editarSource(id,c).pipe(map(unwrapWithMsg));} eliminarSource(id:number){return this.api.eliminarSource(id).pipe(map(unwrapWithMsg));}
  listarSchedules(q='',page=0,size=100,activo:boolean|null=null){return this.api.listarSchedules({q,page,size,activo}).pipe(map(unwrapOrThrow));} crearSchedule(p:Partial<BkpSchedule>){return this.api.crearSchedule(p).pipe(map(unwrapWithMsg));} editarSchedule(id:number,c:Record<string,unknown>){return this.api.editarSchedule(id,c).pipe(map(unwrapWithMsg));} eliminarSchedule(id:number){return this.api.eliminarSchedule(id).pipe(map(unwrapWithMsg));}
  listarIntegrations(q='',page=0,size=100,activo:boolean|null=null){return this.api.listarIntegrations({q,page,size,activo}).pipe(map(unwrapOrThrow));} crearIntegration(p:Partial<BkpIntegrationProvider>){return this.api.crearIntegration(p).pipe(map(unwrapWithMsg));} editarIntegration(id:number,c:Record<string,unknown>){return this.api.editarIntegration(id,c).pipe(map(unwrapWithMsg));} eliminarIntegration(id:number){return this.api.eliminarIntegration(id).pipe(map(unwrapWithMsg));}
  listarDestinations(q='',page=0,size=100,activo:boolean|null=null){return this.api.listarDestinations({q,page,size,activo}).pipe(map(unwrapOrThrow));} crearDestination(p:Partial<BkpStorageDestination>){return this.api.crearDestination(p).pipe(map(unwrapWithMsg));} editarDestination(id:number,c:Record<string,unknown>){return this.api.editarDestination(id,c).pipe(map(unwrapWithMsg));} eliminarDestination(id:number){return this.api.eliminarDestination(id).pipe(map(unwrapWithMsg));}
  listarPlans(q='',page=0,size=100,activo:boolean|null=null){return this.api.listarPlans({q,page,size,activo}).pipe(map(unwrapOrThrow));} obtenerPlan(id:number){return this.api.obtenerPlan(id).pipe(map(unwrapOrThrow));} crearPlan(p:BkpPlanGuardarRequest){return this.api.crearPlan(p).pipe(map(unwrapWithMsg));} editarPlan(id:number,c:Record<string,unknown>){return this.api.editarPlan(id,c).pipe(map(unwrapWithMsg));} reemplazarPlanDestinations(id:number,d:number[]){return this.api.reemplazarPlanDestinations(id,d).pipe(map(unwrapWithMsg));} eliminarPlan(id:number){return this.api.eliminarPlan(id).pipe(map(unwrapWithMsg));}
  listarRuns(q='',page=0,size=100,status:string|null=null){return this.api.listarRuns({q,page,size,status}).pipe(map(unwrapOrThrow));} obtenerRun(id:number){return this.api.obtenerRun(id).pipe(map(unwrapOrThrow));} obtenerRunDetail(id:number){return this.api.obtenerRunDetail(id).pipe(map(unwrapOrThrow));} ejecutarPlan(id:number){return this.api.ejecutarPlan(id).pipe(map(unwrapWithMsg));}
  listarRestores(q='',page=0,size=100,status:string|null=null){return this.api.listarRestores({q,page,size,status}).pipe(map(unwrapOrThrow));} ejecutarRestore(p:BkpRestoreRequest){return this.api.ejecutarRestore(p).pipe(map(unwrapWithMsg));} registrarRestore(p:BkpRestoreRequest){return this.api.registrarRestore(p).pipe(map(unwrapWithMsg));} ejecutarRestoreRegistrado(id:number){return this.api.ejecutarRestoreRegistrado(id).pipe(map(unwrapWithMsg));}
  listarRetentionRuns(q='',page=0,size=100,status:string|null=null){return this.api.listarRetentionRuns({q,page,size,status}).pipe(map(unwrapOrThrow));} ejecutarRetentionTodos(){return this.api.ejecutarRetentionTodos().pipe(map(unwrapWithMsg));} ejecutarRetentionDestino(id:number){return this.api.ejecutarRetentionDestino(id).pipe(map(unwrapWithMsg));}
  listarContacts(q='',page=0,size=100,activo:boolean|null=null){return this.api.listarContacts({q,page,size,activo}).pipe(map(unwrapOrThrow));} crearContact(p:Partial<BkpNotificationContact>){return this.api.crearContact(p).pipe(map(unwrapWithMsg));} editarContact(id:number,c:Record<string,unknown>){return this.api.editarContact(id,c).pipe(map(unwrapWithMsg));} eliminarContact(id:number){return this.api.eliminarContact(id).pipe(map(unwrapWithMsg));}
  listarRules(q='',page=0,size=100,activo:boolean|null=null){return this.api.listarRules({q,page,size,activo}).pipe(map(unwrapOrThrow));} crearRule(p:Partial<BkpNotificationRule>){return this.api.crearRule(p).pipe(map(unwrapWithMsg));} editarRule(id:number,c:Record<string,unknown>){return this.api.editarRule(id,c).pipe(map(unwrapWithMsg));} eliminarRule(id:number){return this.api.eliminarRule(id).pipe(map(unwrapWithMsg));}
  listarGeneralConfig(q='',page=0,size=20,activo:boolean|null=null){return this.api.listarGeneralConfig({q,page,size,activo}).pipe(map(unwrapOrThrow));} crearGeneralConfig(p:Partial<BkpGeneralConfig>){return this.api.crearGeneralConfig(p).pipe(map(unwrapWithMsg));} editarGeneralConfig(id:number,c:Record<string,unknown>){return this.api.editarGeneralConfig(id,c).pipe(map(unwrapWithMsg));} eliminarGeneralConfig(id:number){return this.api.eliminarGeneralConfig(id).pipe(map(unwrapWithMsg));}
}
