export type BkpOption = { value: string; label: string; hint?: string };
export const BKP_ALLOWED_STORAGE_TYPES = ['LOCAL','SFTP','SSH','SCP','S3','GOOGLE_DRIVE'];
export const BKP_ALLOWED_BACKUP_TYPES = ['LOGICAL_FULL','SCHEMA_ONLY','DATA_ONLY','PARTIAL'];
export const BKP_ALLOWED_PG_FORMATS = ['CUSTOM','SQL','TAR'];
export const BKP_ALLOWED_MYSQL_FORMATS = ['SQL'];
export const BKP_ALLOWED_COMPRESSION_TYPES = ['NONE','GZIP'];
export function uniq(values: string[]) { return Array.from(new Set(values.filter(Boolean).map(v => String(v).trim().toUpperCase()))); }
export function storageTypesFromCatalog(c: any): string[] { const raw = uniq([...(c?.implementedStorageTypes ?? []), ...(c?.storageTypes ?? [])]); const merged = raw.length ? raw : BKP_ALLOWED_STORAGE_TYPES; return merged.filter(v => BKP_ALLOWED_STORAGE_TYPES.includes(v)); }
export function backupTypesFromCatalog(c: any): string[] { const raw = uniq(c?.backupTypes ?? []); const merged = raw.length ? raw : BKP_ALLOWED_BACKUP_TYPES; return merged.filter(v => BKP_ALLOWED_BACKUP_TYPES.includes(v)); }
export function formatsForMotor(motor?: string | null): string[] { return String(motor || '').toUpperCase() === 'MYSQL' ? BKP_ALLOWED_MYSQL_FORMATS : BKP_ALLOWED_PG_FORMATS; }
export function compressionTypesFromCatalog(c: any): string[] { const raw = uniq(c?.compressionTypes ?? []); const merged = raw.length ? raw : BKP_ALLOWED_COMPRESSION_TYPES; return merged.filter(v => BKP_ALLOWED_COMPRESSION_TYPES.includes(v)); }
export function labelStorageType(v?: string | null) { const x=String(v||'').toUpperCase(); return ({LOCAL:'Local',SFTP:'SFTP',SSH:'SSH / SCP',SCP:'SCP',S3:'Amazon S3 / compatible',GOOGLE_DRIVE:'Google Drive'} as Record<string,string>)[x] ?? x; }
export function labelBackupType(v?: string | null) { const x=String(v||'').toUpperCase(); return ({LOGICAL_FULL:'Completo lógico',SCHEMA_ONLY:'Solo estructura',DATA_ONLY:'Solo datos',PARTIAL:'Parcial / tablas'} as Record<string,string>)[x] ?? x; }
export function labelFormat(v?: string | null) { const x=String(v||'').toUpperCase(); return ({CUSTOM:'CUSTOM recomendado',SQL:'SQL plano',TAR:'TAR'} as Record<string,string>)[x] ?? x; }
export function labelCompression(v?: string | null) { const x=String(v||'').toUpperCase(); return ({NONE:'Sin compresión',GZIP:'GZIP'} as Record<string,string>)[x] ?? x; }
export function labelScheduleType(v?: string | null) { const x=String(v||'').toUpperCase(); return ({HOURLY:'Cada hora',DAILY:'Diario',WEEKLY:'Semanal',MONTHLY:'Mensual',INTERVAL:'Cada X minutos',CRON:'Cron avanzado'} as Record<string,string>)[x] ?? x; }
export function labelSecretType(v?: string | null) { const x=String(v||'').toUpperCase(); return ({DB_PASSWORD:'Contraseña de base de datos',ENCRYPTION_KEY:'Clave de cifrado de backups',SSH_PASSWORD:'Password SSH/SFTP',SSH_PRIVATE_KEY:'Clave privada SSH/SFTP',GOOGLE_TOKEN:'Token Google Drive',S3_ACCESS_KEY:'Credenciales S3',WEBHOOK_TOKEN:'Token Webhook',API_TOKEN:'Token API'} as Record<string,string>)[x] ?? x; }
export function secretHelp(v?: string | null) { const x=String(v||'').toUpperCase(); if(x==='S3_ACCESS_KEY')return 'Usa JSON {"accessKey":"...","secretKey":"..."} o accessKey:secretKey.'; if(x==='SSH_PASSWORD')return 'Puedes guardar solo la contraseña o JSON {"password":"..."}.'; if(x==='SSH_PRIVATE_KEY')return 'Si la llave tiene clave, usa JSON {"passphrase":"..."}. La ruta va en el destino.'; if(x==='GOOGLE_TOKEN')return 'Access token OAuth usado para subir a Google Drive.'; if(x==='ENCRYPTION_KEY')return 'Clave usada para cifrar el archivo final del backup.'; return 'El valor se guarda cifrado y no se volverá a mostrar.'; }
export function jsonPretty(value: unknown, fallback = '{}') { try { return JSON.stringify(value ?? JSON.parse(fallback), null, 2); } catch { return fallback; } }
export function parseJsonObjectStrict(value: unknown, label = 'JSON'): Record<string, unknown> { if(!value)return{}; if(typeof value==='object'&&!Array.isArray(value))return value as Record<string,unknown>; try{const p=JSON.parse(String(value)); if(!p||typeof p!=='object'||Array.isArray(p))throw new Error('debe ser un objeto'); return p as Record<string,unknown>;}catch(e){const m=e instanceof Error?e.message:'JSON inválido'; throw new Error(`${label} inválido: ${m}`);} }
export function parseJsonArrayStrict(value: unknown, label = 'JSON'): unknown[] { if(!value)return[]; if(Array.isArray(value))return value; try{const p=JSON.parse(String(value)); if(!Array.isArray(p))throw new Error('debe ser un arreglo'); return p;}catch(e){const m=e instanceof Error?e.message:'JSON inválido'; throw new Error(`${label} inválido: ${m}`);} }
export function toNumberOrNull(value: unknown): number | null { if(value===null||value===undefined||String(value).trim()==='')return null; const n=Number(value); return Number.isFinite(n)?n:null; }
export function toNullableString(value: unknown): string | null { const s=value===null||value===undefined?'':String(value).trim(); return s?s:null; }
export function destinationTypeHint(t?: string | null) { const x=String(t||'').toUpperCase(); if(x==='LOCAL')return 'Guarda el archivo en una ruta del servidor KLAX API.'; if(x==='SFTP')return 'Sube el archivo por SFTP a un servidor remoto.'; if(x==='SSH'||x==='SCP')return 'Copia el archivo por SSH/SCP a un servidor remoto.'; if(x==='S3')return 'Sube el archivo a un bucket S3 o compatible.'; if(x==='GOOGLE_DRIVE')return 'Sube el archivo a una carpeta Google Drive.'; return 'Selecciona dónde se guardará el archivo final.'; }
export function fmtBytes(value?: number|null) { const n=Number(value??0); if(!n)return '0 B'; const u=['B','KB','MB','GB','TB']; let i=0,s=n; while(s>=1024&&i<u.length-1){s/=1024;i++;} return `${s.toFixed(s>=10||i===0?0:1)} ${u[i]}`; }
export function fmtDate(value?: string|null) { if(!value)return '-'; try{return new Date(value).toLocaleString();}catch{return String(value);} }
