import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { forkJoin, finalize } from 'rxjs';
import { ButtonModule } from 'primeng/button';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import { InputTextModule } from 'primeng/inputtext';
import { TextareaModule } from 'primeng/textarea';
import { BkpPageHeaderComponent } from '../../components/bkp-ui.component';
import { BkpRepository } from '../../data-access/bkp.repository';
import { BkpConfirmService } from '../../services/bkp-confirm.service';
import { PendingChangesAware } from '../../guards/pending-changes.guard';
import { jsonPretty, parseJsonObject } from '../../data-access/bkp.shared';
import { NotifyService } from 'src/app/core/services/notify.service';
@Component({selector:'app-bkp-agents',standalone:true,imports:[CommonModule,FormsModule,ButtonModule,ConfirmDialogModule,InputTextModule,TextareaModule,BkpPageHeaderComponent],templateUrl:'./agents.component.html',styleUrl:'./agents.component.scss'})
export class BkpAgentsComponent implements OnInit,PendingChangesAware{private repo=inject(BkpRepository);private confirm=inject(BkpConfirmService);private notify=inject(NotifyService);tab=signal<'agents'|'tools'>('agents');loading=signal(false);saving=signal(false);dirty=signal(false);agents=signal<any[]>([]);tools=signal<any[]>([]);selected=signal<any|null>(null);jsonText=signal('{}');initial='{}';ngOnInit(){this.cargar();}canDeactivate(){return !this.dirty()||this.confirm.confirmDiscard();}cargar(){this.loading.set(true);forkJoin({agents:this.repo.listarAgents('',0,100,null),tools:this.repo.listarTools('',0,100,null)}).pipe(finalize(()=>this.loading.set(false))).subscribe({next:(r:any)=>{this.agents.set(r.agents.items??[]);this.tools.set(r.tools.items??[]);},error:(e:any)=>this.notify.error('No se pudo cargar agentes',e?.message)});}items(){return this.tab()==='agents'?this.agents():this.tools();}idField(){return this.tab()==='agents'?'idBkpAgentNode':'idBkpEngineTool';}nuevo(){this.selected.set(null);this.jsonText.set(jsonPretty(this.tab()==='agents'?{nombre:'BACKUP-SERVER-01',osType:'LINUX',workDir:'/opt/backup-agent',tempDir:'/var/backups/tmp',maxParallelJobs:1,metadata:{},activo:true}:{idBkpAgentNodeFk:null,motor:'POSTGRESQL',herramienta:'pg_dump',binaryPath:'/usr/bin/pg_dump',configJson:{},activo:true}));this.refresh();}seleccionar(i:any){this.selected.set(i);this.jsonText.set(jsonPretty(i));this.refresh();}guardar(){const p=parseJsonObject(this.jsonText());const id=Number(this.selected()?.[this.idField()]??0);delete (p as any)[this.idField()];this.saving.set(true);const req:any=this.tab()==='agents'?(id?this.repo.editarAgent(id,p):this.repo.crearAgent(p)):(id?this.repo.editarTool(id,p):this.repo.crearTool(p));req.pipe(finalize(()=>this.saving.set(false))).subscribe({next:(r:any)=>{this.notify.success('Guardado',r.mensaje);this.dirty.set(false);this.cargar();},error:(e:any)=>this.notify.error('No se pudo guardar',e?.message)});}onChange(v:string){this.jsonText.set(v);this.dirty.set(v!==this.initial);}refresh(){this.initial=this.jsonText();this.dirty.set(false);}}
