import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { finalize, forkJoin } from 'rxjs';
import { ButtonModule } from 'primeng/button';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import { BkpPageHeaderComponent, BkpEmptyStateComponent } from '../../components/bkp-ui.component';
import { BkpRepository } from '../../data-access/bkp.repository';
import { BkpAgentNode, BkpEngineTool, BkpCatalogs } from '../../data-access/bkp.models';
import { BkpConfirmService } from '../../services/bkp-confirm.service';
import { PendingChangesAware } from '../../guards/pending-changes.guard';
import { jsonPretty, parseJsonObjectStrict } from '../../data-access/bkp.shared';
import { NotifyService } from 'src/app/core/services/notify.service';

@Component({selector:'app-bkp-agents',standalone:true,imports:[CommonModule,ReactiveFormsModule,ButtonModule,ConfirmDialogModule,BkpPageHeaderComponent,BkpEmptyStateComponent],templateUrl:'./agents.component.html',styleUrl:'./agents.component.scss'})
export class BkpAgentsComponent implements OnInit, PendingChangesAware {
  private repo=inject(BkpRepository); private confirm=inject(BkpConfirmService); private notify=inject(NotifyService); private fb=inject(FormBuilder);
  tab=signal<'agents'|'tools'>('agents'); loading=signal(false); saving=signal(false); dirty=signal(false); error=signal<string|null>(null); success=signal<string|null>(null);
  agents=signal<BkpAgentNode[]>([]); tools=signal<BkpEngineTool[]>([]); catalogs=signal<Partial<BkpCatalogs>>({}); selectedAgent=signal<BkpAgentNode|null>(null); selectedTool=signal<BkpEngineTool|null>(null);
  agentForm=this.fb.group({nombre:['',Validators.required],hostname:[''],ipAddress:[''],osType:['LINUX',Validators.required],workDir:['/opt/backup-agent'],tempDir:['/var/backups/tmp'],logDir:[''],maxParallelJobs:[1,[Validators.required,Validators.min(1),Validators.max(20)]],observacion:[''],metadataJson:['{}'],activo:[true]});
  toolForm=this.fb.group({idBkpAgentNodeFk:[null as number|null,Validators.required],motor:['POSTGRESQL',Validators.required],herramienta:['pg_dump',Validators.required],binaryPath:['/usr/bin/pg_dump',Validators.required],versionText:[''],configJson:['{}'],activo:[true]});
  ngOnInit(){this.agentForm.valueChanges.subscribe(()=>this.markDirty());this.toolForm.valueChanges.subscribe(()=>this.markDirty());this.cargar();this.nuevo();}
  canDeactivate(){return !this.dirty()||this.confirm.confirmDiscard();}
  cargar(){this.loading.set(true);forkJoin({agents:this.repo.listarAgents('',0,200,null),tools:this.repo.listarTools('',0,200,null),catalogs:this.repo.catalogos()}).pipe(finalize(()=>this.loading.set(false))).subscribe({next:r=>{this.agents.set(r.agents.items??[]);this.tools.set(r.tools.items??[]);this.catalogs.set(r.catalogs??{});},error:e=>this.setError('No se pudo cargar agentes',e?.message)});}
  async setTab(t:'agents'|'tools'){if(this.dirty()&&!(await this.confirm.confirmDiscard()))return;this.tab.set(t);this.nuevo();}
  nuevo(){this.selectedAgent.set(null);this.selectedTool.set(null);this.agentForm.reset({nombre:'BACKUP-SERVER-01',hostname:'',ipAddress:'',osType:'LINUX',workDir:'/opt/backup-agent',tempDir:'/var/backups/tmp',logDir:'',maxParallelJobs:1,observacion:'',metadataJson:'{}',activo:true});this.toolForm.reset({idBkpAgentNodeFk:this.agents()[0]?.idBkpAgentNode??null,motor:'POSTGRESQL',herramienta:'pg_dump',binaryPath:'/usr/bin/pg_dump',versionText:'',configJson:'{}',activo:true});this.clean();}
  async seleccionarAgent(i:BkpAgentNode){if(this.dirty()&&!(await this.confirm.confirmDiscard()))return;this.tab.set('agents');this.selectedAgent.set(i);this.selectedTool.set(null);this.agentForm.reset({nombre:i.nombre??'',hostname:i.hostname??'',ipAddress:i.ipAddress??'',osType:i.osType??'LINUX',workDir:i.workDir??'',tempDir:i.tempDir??'',logDir:i.logDir??'',maxParallelJobs:i.maxParallelJobs??1,observacion:i.observacion??'',metadataJson:jsonPretty(i.metadata??{}),activo:i.activo!==false});this.clean();}
  async seleccionarTool(i:BkpEngineTool){if(this.dirty()&&!(await this.confirm.confirmDiscard()))return;this.tab.set('tools');this.selectedTool.set(i);this.selectedAgent.set(null);this.toolForm.reset({idBkpAgentNodeFk:i.idBkpAgentNodeFk??null,motor:i.motor??'POSTGRESQL',herramienta:i.herramienta??'pg_dump',binaryPath:i.binaryPath??'',versionText:i.versionText??'',configJson:jsonPretty(i.configJson??{}),activo:i.activo!==false});this.clean();}
  guardarAgent(){this.agentForm.markAllAsTouched();if(this.agentForm.invalid){this.setError('Completa los campos obligatorios del agente.');return;}let metadata:Record<string,unknown>;try{metadata=parseJsonObjectStrict(this.agentForm.value.metadataJson,'Metadata');}catch(e){this.setError(e instanceof Error?e.message:'JSON inválido');return;}const v=this.agentForm.getRawValue();const p:Partial<BkpAgentNode>={nombre:v.nombre??'',hostname:v.hostname||null,ipAddress:v.ipAddress||null,osType:v.osType??'LINUX',workDir:v.workDir||null,tempDir:v.tempDir||null,logDir:v.logDir||null,maxParallelJobs:Number(v.maxParallelJobs??1),observacion:v.observacion||null,metadata,activo:v.activo??true};const id=this.selectedAgent()?.idBkpAgentNode??0;this.save(id?this.repo.editarAgent(id,p as Record<string,unknown>):this.repo.crearAgent(p),'Agente guardado');}
  guardarTool(){this.toolForm.markAllAsTouched();if(this.toolForm.invalid){this.setError('Completa agente, motor, herramienta y ruta.');return;}let configJson:Record<string,unknown>;try{configJson=parseJsonObjectStrict(this.toolForm.value.configJson,'Config JSON');}catch(e){this.setError(e instanceof Error?e.message:'JSON inválido');return;}const v=this.toolForm.getRawValue();const p:Partial<BkpEngineTool>={idBkpAgentNodeFk:Number(v.idBkpAgentNodeFk),motor:v.motor??'POSTGRESQL',herramienta:v.herramienta??'pg_dump',binaryPath:v.binaryPath??'',versionText:v.versionText||null,configJson,activo:v.activo??true};const id=this.selectedTool()?.idBkpEngineTool??0;this.save(id?this.repo.editarTool(id,p as Record<string,unknown>):this.repo.crearTool(p),'Binario guardado');}
  async eliminarAgent(i=this.selectedAgent()){if(!i)return;if(!(await this.confirm.confirmDelete(i.nombre)))return;this.save(this.repo.eliminarAgent(i.idBkpAgentNode),'Agente desactivado',true);}
  async eliminarTool(i=this.selectedTool()){if(!i)return;if(!(await this.confirm.confirmDelete(i.herramienta)))return;this.save(this.repo.eliminarTool(i.idBkpEngineTool),'Binario desactivado',true);}
  save(obs:any,label:string,reset=false){this.saving.set(true);obs.pipe(finalize(()=>this.saving.set(false))).subscribe({next:(r:any)=>{this.success.set(r?.mensaje||label);this.notify.success(label,r?.mensaje);this.dirty.set(false);if(reset)this.nuevo();this.cargar();},error:(e:any)=>this.setError('No se pudo guardar',e?.message)});}
  clean(){this.dirty.set(false);this.error.set(null);this.success.set(null);} markDirty(){this.dirty.set(true);this.success.set(null);} setError(s:string,d?:string){this.error.set(d||s);this.notify.error(s,d);}
  motores(){return this.catalogs().motores??['POSTGRESQL','MYSQL'];} herramientas(){return this.catalogs().herramientas??['pg_dump','pg_restore','psql','mysqldump','mysql'];} agentName(id?:number|null){return this.agents().find(a=>a.idBkpAgentNode===id)?.nombre??'Sin agente';}
  invalid(form:'agent'|'tool',n:string){const c=form==='agent'?this.agentForm.get(n):this.toolForm.get(n);return !!c&&c.invalid&&(c.dirty||c.touched);}
}
