import { CommonModule } from '@angular/common';
import { Component, OnInit, inject, signal, computed } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { finalize } from 'rxjs';
import { BkpPageHeaderComponent, BkpEmptyStateComponent } from '../../components/bkp-ui.component';
import { BkpRepository } from '../../data-access/bkp.repository';
import { BkpSecret, BkpStorageDestination } from '../../data-access/bkp.models';
import { destinationTypeHint, jsonPretty, labelSecretType, labelStorageType, parseJsonObjectStrict, storageTypesFromCatalog, toNullableString, toNumberOrNull } from '../../data-access/bkp.ux';
@Component({selector:'app-bkp-destinations',standalone:true,imports:[CommonModule,ReactiveFormsModule,BkpPageHeaderComponent,BkpEmptyStateComponent],templateUrl:'./destinations.component.html',styleUrl:'./destinations.component.scss'})
export class BkpDestinationsComponent implements OnInit{
 private fb=inject(FormBuilder); private repo=inject(BkpRepository); items=signal<BkpStorageDestination[]>([]); secrets=signal<BkpSecret[]>([]); storageTypes=signal<string[]>(['LOCAL','SFTP','SSH','S3','GOOGLE_DRIVE']); selected=signal<BkpStorageDestination|null>(null); q=signal(''); loading=signal(false); saving=signal(false); dirty=signal(false); error=signal(''); success=signal(''); technicalOpen=signal(false);
 form=this.fb.group({nombre:['',Validators.required],tipoStorage:['LOCAL',Validators.required],basePath:['/var/backups/klax'],bucketName:[''],prefixPath:[''],folderId:[''],idBkpSecretCredentialFk:[null as number|null],retentionDays:[30,[Validators.required,Validators.min(1)]],immutableEnabled:[false],immutableDays:[null as number|null],activo:[true],sftpHost:[''],sftpPort:[22],sftpUsername:[''],sftpRemotePath:[''],sftpIdentityFile:[''],sftpStrictHostKey:[false],sftpKnownHosts:[''],s3Region:['us-east-1'],s3EndpointOverride:[''],configJson:['{}']});
 tipo=computed(()=>String(this.form.value.tipoStorage||'LOCAL').toUpperCase()); typeHint=computed(()=>destinationTypeHint(this.tipo()));
 ngOnInit(){this.form.valueChanges.subscribe(()=>this.dirty.set(true));this.cargar();}
 canDeactivate(){return !this.dirty()||confirm('Tienes cambios pendientes. ¿Salir sin guardar?');}
 cargar(){this.loading.set(true);this.error.set('');this.repo.catalogos().subscribe({next:c=>this.storageTypes.set(storageTypesFromCatalog(c)),error:e=>this.error.set(this.msg(e))});this.repo.listarSecrets('',0,300,true).subscribe({next:p=>this.secrets.set(p.items??[]),error:()=>{}});this.repo.listarDestinations(this.q(),0,200,null).pipe(finalize(()=>this.loading.set(false))).subscribe({next:p=>this.items.set(p.items??[]),error:e=>this.error.set(this.msg(e))});}
 nuevo(){this.selected.set(null);this.technicalOpen.set(false);this.form.reset({nombre:'',tipoStorage:'LOCAL',basePath:'/var/backups/klax',bucketName:'',prefixPath:'',folderId:'',idBkpSecretCredentialFk:null,retentionDays:30,immutableEnabled:false,immutableDays:null,activo:true,sftpHost:'',sftpPort:22,sftpUsername:'',sftpRemotePath:'',sftpIdentityFile:'',sftpStrictHostKey:false,sftpKnownHosts:'',s3Region:'us-east-1',s3EndpointOverride:'',configJson:'{}'});this.dirty.set(false);this.error.set('');this.success.set('');}
 seleccionar(i:BkpStorageDestination){this.selected.set(i);const cfg=i.configJson??{};this.form.reset({nombre:i.nombre,tipoStorage:String(i.tipoStorage||'LOCAL').toUpperCase(),basePath:i.basePath??'',bucketName:i.bucketName??'',prefixPath:i.prefixPath??'',folderId:i.folderId??'',idBkpSecretCredentialFk:i.idBkpSecretCredentialFk??null,retentionDays:i.retentionDays??30,immutableEnabled:!!i.immutableEnabled,immutableDays:i.immutableDays??null,activo:i.activo!==false,sftpHost:String(cfg['host']??''),sftpPort:Number(cfg['port']??22),sftpUsername:String(cfg['username']??''),sftpRemotePath:String(cfg['remotePath']??''),sftpIdentityFile:String(cfg['identityFile']??''),sftpStrictHostKey:!!cfg['strictHostKey'],sftpKnownHosts:String(cfg['knownHosts']??''),s3Region:String(cfg['region']??'us-east-1'),s3EndpointOverride:String(cfg['endpointOverride']??''),configJson:jsonPretty(cfg)});this.dirty.set(false);this.error.set('');this.success.set('');}
 guardar(){this.error.set('');this.success.set('');try{const payload=this.payload();this.saving.set(true);const id=this.selected()?.idBkpStorageDestination;const op=id?this.repo.editarDestination(id,payload as Record<string,unknown>):this.repo.crearDestination(payload);op.pipe(finalize(()=>this.saving.set(false))).subscribe({next:r=>{this.success.set(r.mensaje);this.dirty.set(false);this.cargar();},error:e=>this.error.set(this.msg(e))});}catch(e){this.error.set(this.msg(e));}}
 eliminar(){const id=this.selected()?.idBkpStorageDestination;if(!id||!confirm('¿Desactivar este destino?'))return;this.saving.set(true);this.repo.eliminarDestination(id).pipe(finalize(()=>this.saving.set(false))).subscribe({next:r=>{this.success.set(r.mensaje);this.nuevo();this.cargar();},error:e=>this.error.set(this.msg(e))});}
 private payload():Partial<BkpStorageDestination>{const v=this.form.getRawValue();const type=String(v.tipoStorage||'').toUpperCase();if(!v.nombre?.trim())throw new Error('Nombre es obligatorio.');if(!type)throw new Error('Tipo de destino es obligatorio.');if(!v.retentionDays||Number(v.retentionDays)<1)throw new Error('Retención días debe ser mayor a 0.');const p:Partial<BkpStorageDestination>={nombre:v.nombre.trim(),tipoStorage:type,prefixPath:toNullableString(v.prefixPath),retentionDays:Number(v.retentionDays),activo:!!v.activo,immutableEnabled:false,immutableDays:null,configJson:{}};if(type==='LOCAL'){if(!v.basePath?.trim())throw new Error('Ruta local es obligatoria para LOCAL.');p.basePath=v.basePath.trim();}if(type==='S3'){if(!v.bucketName?.trim())throw new Error('Bucket es obligatorio para S3.');if(!v.idBkpSecretCredentialFk)throw new Error('Credencial es obligatoria para S3.');p.bucketName=v.bucketName.trim();p.idBkpSecretCredentialFk=v.idBkpSecretCredentialFk;p.immutableEnabled=!!v.immutableEnabled;p.immutableDays=toNumberOrNull(v.immutableDays);p.configJson={...parseJsonObjectStrict(v.configJson,'Config JSON'),region:v.s3Region||'us-east-1',...(v.s3EndpointOverride?{endpointOverride:v.s3EndpointOverride}:{})};}if(type==='GOOGLE_DRIVE'){if(!v.folderId?.trim())throw new Error('Folder ID es obligatorio para Google Drive.');if(!v.idBkpSecretCredentialFk)throw new Error('Token Google es obligatorio.');p.folderId=v.folderId.trim();p.idBkpSecretCredentialFk=v.idBkpSecretCredentialFk;p.configJson=parseJsonObjectStrict(v.configJson,'Config JSON');}if(['SFTP','SSH','SCP'].includes(type)){if(!v.sftpHost?.trim())throw new Error('Host remoto es obligatorio.');if(!v.sftpUsername?.trim())throw new Error('Usuario remoto es obligatorio.');if(!v.sftpRemotePath?.trim())throw new Error('Ruta remota es obligatoria.');if(!v.idBkpSecretCredentialFk&&!v.sftpIdentityFile?.trim())throw new Error('Configura un secreto credencial o un identity file.');p.idBkpSecretCredentialFk=v.idBkpSecretCredentialFk;p.configJson={...parseJsonObjectStrict(v.configJson,'Config JSON'),host:v.sftpHost.trim(),port:Number(v.sftpPort||22),username:v.sftpUsername.trim(),remotePath:v.sftpRemotePath.trim(),...(v.sftpIdentityFile?{identityFile:v.sftpIdentityFile.trim()}:{}),strictHostKey:!!v.sftpStrictHostKey,...(v.sftpKnownHosts?{knownHosts:v.sftpKnownHosts.trim()}:{}),};}return p;}
 labelStorageType=labelStorageType; labelSecretType=labelSecretType; isLocal(){return this.tipo()==='LOCAL';} isS3(){return this.tipo()==='S3';} isDrive(){return this.tipo()==='GOOGLE_DRIVE';} isRemote(){return ['SFTP','SSH','SCP'].includes(this.tipo());} private msg(e:unknown){return e instanceof Error?e.message:String((e as any)?.message||e||'Error');}
}
